[package]
name = "ncn-portal-sdk"
version = "0.1.0"
edition = "2021"

[dependencies]
borsh = { workspace = true }
shank = { workspace = true }
solana-program = { workspace = true }
thiserror = { workspace = true }
