name: Publish Shank IDL Generator

on:
  workflow_dispatch:
    inputs:
      package_path:
        description: Which crate to publish
        required: true
        default: 'shank-idl-generator'
        type: choice
        options:
          - shank-idl-generator
      level:
        description: Version increment level
        required: true
        default: patch
        type: choice
        options:
          - patch
          - minor
          - major
      dry_run:
        description: Dry run (no actual publishing)
        required: true
        default: true
        type: boolean
      create_release:
        description: Create a GitHub release
        required: true
        type: boolean
        default: true

jobs:
  # First job - update version and publish crate
  update-version:
    name: Update Version
    runs-on: ubuntu-latest
    outputs:
      crate_name: ${{ steps.publish.outputs.crate_name }}
      old_version: ${{ steps.publish.outputs.old_version }}
      new_version: ${{ steps.publish.outputs.new_version }}
      new_git_tag: ${{ steps.publish.outputs.new_git_tag }}
    permissions:
      contents: write
    steps:
      - name: Git Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.REPO_PAT }}
          fetch-depth: 0 # get the whole history for changelog

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2
        with:
          key: "shank-publish-${{ inputs.package_path }}"

      - name: Install Cargo Release
        run: cargo install cargo-release

      - name: Set Git Author
        run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

      - name: Extract crate name
        id: extract_name
        run: |
          # Extract just the crate name from the path for use in tags and releases
          CRATE_NAME=$(basename "${{ inputs.package_path }}")
          echo "crate_name=$CRATE_NAME" >> $GITHUB_OUTPUT

      - name: Update Version and Publish Crate
        id: publish
        working-directory: ${{ inputs.package_path }}
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
        run: |
          # Get current version before update
          OLD_VERSION=$(grep -m1 'version =' Cargo.toml | cut -d '"' -f2)
          echo "old_version=${OLD_VERSION}" >> $GITHUB_OUTPUT
          
          if [ "${{ inputs.dry_run }}" == "true" ]; then
            # For dry-run mode, don't use the -x flag (dry-run is default)
            cargo release ${{ inputs.level }} --no-confirm --no-push
          else
            # For actual execution, use the -x flag
            cargo release ${{ inputs.level }} --no-confirm -x
          fi
          
          # Get new version after update
          NEW_VERSION=$(grep -m1 'version =' Cargo.toml | cut -d '"' -f2)
          
          # Set outputs for the release step
          echo "crate_name=${{ steps.extract_name.outputs.crate_name }}" >> $GITHUB_OUTPUT
          echo "new_version=${NEW_VERSION}" >> $GITHUB_OUTPUT
          echo "new_git_tag=${{ steps.extract_name.outputs.crate_name }}-v${NEW_VERSION}" >> $GITHUB_OUTPUT
          
          # Echo the versions for debug
          echo "Old version: ${OLD_VERSION}, New version: ${NEW_VERSION}"

  # Second job - build binaries with new version
  build-binaries:
    name: Build ${{ matrix.target }}
    needs: update-version
    runs-on: ${{ matrix.os }}
    if: github.event.inputs.create_release == 'true'
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-musl
            name: x86_64-unknown-linux-musl
          - os: macos-latest
            target: x86_64-apple-darwin
            name: x86_64-apple-darwin
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            name: x86_64-pc-windows-msvc
    steps:
      - name: Git Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ needs.update-version.outputs.new_git_tag }}
      
      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}
      
      - name: Install musl-tools (Linux only)
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get update && sudo apt-get install -y musl-tools
      
      - name: Rust Cache
        uses: Swatinem/rust-cache@v2
        with:
          key: "shank-build-${{ matrix.target }}-${{ inputs.package_path }}"
      
      - name: Build
        working-directory: ${{ inputs.package_path }}
        run: cargo build --release --target ${{ matrix.target }}
      
      - name: Prepare binary (Unix)
        if: matrix.os != 'windows-latest'
        run: |
          CRATE_NAME="${{ needs.update-version.outputs.crate_name }}"
          VERSION="${{ needs.update-version.outputs.new_version }}"
          BINARY_NAME="${CRATE_NAME}-v${VERSION}-${{ matrix.target }}"
          
          echo "Building binary with new version: $VERSION"
          
          # Copy binary to root with appropriate name
          cp ./target/${{ matrix.target }}/release/${CRATE_NAME} ${BINARY_NAME}
          
          # Create checksum
          shasum -a 256 ${BINARY_NAME} > ${BINARY_NAME}.sha256
      
      - name: Prepare binary (Windows)
        if: matrix.os == 'windows-latest'
        shell: pwsh
        run: |
          $CRATE_NAME = "${{ needs.update-version.outputs.crate_name }}"
          $VERSION = "${{ needs.update-version.outputs.new_version }}"
          $BINARY_NAME = "${CRATE_NAME}-v${VERSION}-${{ matrix.target }}.exe"
          
          Write-Host "Building binary with new version: $VERSION"
          
          # Copy binary to root with appropriate name
          Copy-Item "./target/${{ matrix.target }}/release/${CRATE_NAME}.exe" -Destination $BINARY_NAME
          
          # Create checksum
          $hash = Get-FileHash -Path $BINARY_NAME -Algorithm SHA256
          $hash.Hash | Out-File -FilePath "${BINARY_NAME}.sha256"
      
      - name: Upload binary artifacts (Unix)
        if: matrix.os != 'windows-latest'
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.name }}
          path: |
            ${{ needs.update-version.outputs.crate_name }}-v${{ needs.update-version.outputs.new_version }}-${{ matrix.target }}
            ${{ needs.update-version.outputs.crate_name }}-v${{ needs.update-version.outputs.new_version }}-${{ matrix.target }}.sha256
          retention-days: 7
      
      - name: Upload binary artifacts (Windows)
        if: matrix.os == 'windows-latest'
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.name }}
          path: |
            ${{ needs.update-version.outputs.crate_name }}-v${{ needs.update-version.outputs.new_version }}-${{ matrix.target }}.exe
            ${{ needs.update-version.outputs.crate_name }}-v${{ needs.update-version.outputs.new_version }}-${{ matrix.target }}.exe.sha256
          retention-days: 7

  # Third job - Create GitHub release
  create-release:
    name: Create GitHub Release
    needs: [update-version, build-binaries]
    runs-on: ubuntu-latest
    if: github.event.inputs.create_release == 'true' && github.event.inputs.dry_run != 'true'
    permissions:
      contents: write
    steps:
      - name: Git Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.REPO_PAT }}
          fetch-depth: 0 # get the whole history for changelog
          ref: ${{ needs.update-version.outputs.new_git_tag }}

      - name: Create release directory
        run: mkdir -p release-binaries

      - name: Download Linux binary
        uses: actions/download-artifact@v4
        with:
          name: x86_64-unknown-linux-musl
          path: release-binaries

      - name: Download macOS binary
        uses: actions/download-artifact@v4
        with:
          name: x86_64-apple-darwin
          path: release-binaries

      - name: Download Windows binary
        uses: actions/download-artifact@v4
        with:
          name: x86_64-pc-windows-msvc
          path: release-binaries

      - name: List release files
        run: |
          echo "Contents of release-binaries directory:"
          ls -la release-binaries/

      - name: Generate a changelog
        id: changelog
        uses: metcalfc/changelog-generator@v4.1.0
        with:
          myToken: ${{ secrets.REPO_PAT }}
          includePattern: ".*/${{ inputs.package_path }}/.*"

      - name: Create GitHub release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ needs.update-version.outputs.new_git_tag }}
          name: "${{ needs.update-version.outputs.crate_name }} v${{ needs.update-version.outputs.new_version }}"
          body: ${{ steps.changelog.outputs.changelog }}
          artifacts: "./release-binaries/*"
          artifactErrorsFailBuild: false