name: Publish Shank IDL Generator Crate

on:
  workflow_dispatch:
    inputs:
      package_path:
        description: Which crate to publish
        required: true
        default: 'shank-idl-generator'
        type: choice
        options:
          - shank-idl-generator
      level:
        description: Version increment level
        required: true
        default: patch
        type: choice
        options:
          - patch
          - minor
          - major
      dry_run:
        description: Dry run (no actual publishing)
        required: true
        default: true
        type: boolean
      create_release:
        description: Create a GitHub release
        required: true
        type: boolean
        default: true

jobs:
  # Update version and publish crate
  publish-crate:
    name: Update Version and Publish
    runs-on: ubuntu-latest
    outputs:
      crate_name: ${{ steps.publish.outputs.crate_name }}
      old_version: ${{ steps.publish.outputs.old_version }}
      new_version: ${{ steps.publish.outputs.new_version }}
      new_git_tag: ${{ steps.publish.outputs.new_git_tag }}
    permissions:
      contents: write
    steps:
      - name: Git Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.REPO_PAT }}
          fetch-depth: 0 # get the whole history for changelog

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2
        with:
          key: "shank-publish-${{ inputs.package_path }}"

      - name: Install Cargo Release
        run: cargo install cargo-release

      - name: Set Git Author
        run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

      - name: Extract crate name
        id: extract_name
        run: |
          # Extract just the crate name from the path for use in tags and releases
          CRATE_NAME=$(basename "${{ inputs.package_path }}")
          echo "crate_name=$CRATE_NAME" >> $GITHUB_OUTPUT

      - name: Update Version and Publish Crate
        id: publish
        working-directory: ${{ inputs.package_path }}
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
        run: |
          # Get current version before update
          OLD_VERSION=$(grep -m1 'version =' Cargo.toml | cut -d '"' -f2)
          echo "old_version=${OLD_VERSION}" >> $GITHUB_OUTPUT
          
          if [ "${{ inputs.dry_run }}" == "true" ]; then
            # For dry-run mode, don't use the -x flag (dry-run is default)
            cargo release ${{ inputs.level }} --no-confirm --no-push
          else
            # For actual execution, use the -x flag
            cargo release ${{ inputs.level }} --no-confirm -x
          fi
          
          # Get new version after update
          NEW_VERSION=$(grep -m1 'version =' Cargo.toml | cut -d '"' -f2)
          
          # Set outputs for the release step
          echo "crate_name=${{ steps.extract_name.outputs.crate_name }}" >> $GITHUB_OUTPUT
          echo "new_version=${NEW_VERSION}" >> $GITHUB_OUTPUT
          echo "new_git_tag=${{ steps.extract_name.outputs.crate_name }}-v${NEW_VERSION}" >> $GITHUB_OUTPUT
          
          # Echo the versions for debug
          echo "Old version: ${OLD_VERSION}, New version: ${NEW_VERSION}"

  # Create GitHub release (without binaries)
  create-release:
    name: Create GitHub Release
    needs: publish-crate
    runs-on: ubuntu-latest
    if: github.event.inputs.create_release == 'true' && github.event.inputs.dry_run != 'true'
    permissions:
      contents: write
    steps:
      - name: Git Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.REPO_PAT }}
          fetch-depth: 0 # get the whole history for changelog
          ref: ${{ needs.publish-crate.outputs.new_git_tag }}

      - name: Generate a changelog
        id: changelog
        uses: metcalfc/changelog-generator@v4.1.0
        with:
          myToken: ${{ secrets.REPO_PAT }}
          includePattern: ".*/${{ inputs.package_path }}/.*"

      - name: Create GitHub release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ needs.publish-crate.outputs.new_git_tag }}
          name: "${{ needs.publish-crate.outputs.crate_name }} v${{ needs.publish-crate.outputs.new_version }}"
          body: ${{ steps.changelog.outputs.changelog }}
          draft: true

      - name: Echo release information
        run: |
          echo "Created draft release for ${{ needs.publish-crate.outputs.crate_name }} v${{ needs.publish-crate.outputs.new_version }}"
          echo "Tag: ${{ needs.publish-crate.outputs.new_git_tag }}"
          echo "To build and upload binaries, run the 'Build and Upload Binaries' workflow and specify this tag."